services:
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Services URLs
      - AUTH_SERVICE_URL=http://auth-service:5001
      - CHAT_SERVICE_URL=http://chat-service:5002
      - MANAGEMENT_SERVICE_URL=http://chat-management-service:5004
      # Redis
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      # Logging
      - LOG_LEVEL=info
      - LOG_DIR=logs
      # CORS
      - CORS_ORIGINS=http://localhost:3000
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./logs:/app/logs
    networks:
      - gateway-network
      - shared-infrastructure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  gateway-network:
    driver: bridge
  shared-infrastructure:
    external: true
    name: shared-infrastructure