name: Deploy
on: push

jobs:
  deploy-server1:
    name: Deploy to Server 1
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_GATEWAY_HOST_1 }}
          username: ubuntu
          key_format: PEM
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/api-gateway && \
            git pull origin main && \
            sudo npm install && \
            sudo pm2 delete all || true && \
            sudo rm -rf ~/api-gateway/logs && \
            sudo rm -rf ~/api-gateway/uploads && \
            sudo mkdir -p ~/api-gateway/logs && \
            sudo mkdir -p ~/api-gateway/uploads && \
            sudo setcap 'cap_net_bind_service=+ep' $(which node) && \
            sudo pm2 start src/app.js -i 0

  deploy-server2:
    name: Deploy to Server 2
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_GATEWAY_HOST_2 }}
          username: ubuntu
          key_format: PEM
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/api-gateway && \
            git pull origin main && \
            sudo npm install && \
            sudo pm2 delete all || true && \
            sudo rm -rf ~/api-gateway/logs && \
            sudo rm -rf ~/api-gateway/uploads && \
            sudo mkdir -p ~/api-gateway/logs && \
            sudo mkdir -p ~/api-gateway/uploads && \
            sudo setcap 'cap_net_bind_service=+ep' $(which node) && \
            sudo pm2 start src/app.js -i 0

  deploy-server3:
    name: Deploy to Server 3
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to Server 3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_GATEWAY_HOST_3 }}
          username: ubuntu
          key_format: PEM
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/api-gateway && \
            git pull origin main && \
            sudo npm install && \
            sudo pm2 delete all || true && \
            sudo rm -rf ~/api-gateway/logs && \
            sudo rm -rf ~/api-gateway/uploads && \
            sudo mkdir -p ~/api-gateway/logs && \
            sudo mkdir -p ~/api-gateway/uploads && \
            sudo setcap 'cap_net_bind_service=+ep' $(which node) && \
            sudo pm2 start src/app.js -i 0