name: Deploy
on: push

jobs:
  deploy:
    name: Deploy to EC2
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: "Server 1"
            host: ${{ secrets.API_GATEWAY_HOST_1 }}
          - name: "Server 2"
            host: ${{ secrets.API_GATEWAY_HOST_2 }}
          - name: "Server 3"
            host: ${{ secrets.API_GATEWAY_HOST_3 }}
    steps:
      - name: Deploy to ${{ matrix.name }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.host }}
          username: ubuntu
          key_format: PEM
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/api-gateway && \
            git pull origin main && \
            npm install && \
            sudo pm2 delete all || true && \
            sudo rm -rf ~/api-gateway/logs && \
            sudo rm -rf ~/api-gateway/uploads && \
            sudo mkdir -p ~/api-gateway/logs && \
            sudo mkdir -p ~/api-gateway/uploads && \
            sudo setcap 'cap_net_bind_service=+ep' $(which node) && \
            sudo pm2 start src/app.js -i 0
